export const FETCH_REPAIRER = "FETCH_REPAIRER";
export const REPAIRER_LOGIN_START = "FETCH_REPAIRER_START";
export const REPAIRER_LOGIN_SUCCESS = "FETCH_REPAIRER_SUCCESS";

export const REPAIRER_LOGIN_ERRORS = "REPAIRER_LOGIN_ERRORS";
export const SET_REPAIRER_FROM_JWT = "SET_REPAIRER_FROM_JWT";
export const LOGOUT_REPAIRER = "LOGOUT_REPAIRER";

export const FETCH_ALL_CLIENTS = "FETCH_ALL_CLIENTS";
export const FETCH_ALL_CLIENTS_SUCCESS = "FETCH_ALL_CLIENTS_SUCCESS";

export const FETCH_SINGLE_CLIENT = "FETCH_SINGLE_CLIENT";
export const FETCH_SINGLE_CLIENT_SUCCESS = "FETCH_SINGLE_CLIENT_SUCCESS";

export const CLEAR_ALL_CLIENTS = "CLEAR_ALL_CLIENTS";
