export const FETCH_REPAIRER = "FETCH_REPAIRER";
export const REPAIRER_LOGIN_START = "FETCH_REPAIRER_START";
export const REPAIRER_LOGIN_SUCCESS = "FETCH_REPAIRER_SUCCESS";

export const REPAIRER_LOGIN_ERRORS = "REPAIRER_LOGIN_ERRORS";
export const SET_REPAIRER_FROM_JWT = "SET_REPAIRER_FROM_JWT"